package(default_visibility = ["//visibility:public"])

cc_library(
    name = "message",
    srcs = ["message.cc"],
    hdrs = ["message.h"],
)

cc_library(
    name = "uc_module",
    hdrs = ["uc_module.h"],
    deps = [":message"],
)
